pull_request_rules:
  - name: backport patches to stable branch
    conditions:
      - base=master
      - label=backport
    actions:
      backport:
        branches:
          - stable
          - dev
