pull_request_rules:
  - name: backport patches to stable branch
    conditions:
      - base=master
      - label=backport
    actions:
      backport:
        branches:
          - stable
          - dev

  - name: automatic merge on CircleCI success
    conditions:
      - "status-success=ci/circleci: validate"
      - base=master
    actions:
      merge:
        method: merge
