pull_request_rules:
  - name: backport patches to stable branch
    conditions:
      - base=master
      - label=backport
    actions:
      backport:
        branches:
          - stage
          - dev

  - name: automatic merge on CircleCI success
    conditions:
      - "status-success=ci/circleci: validate"
      - base=master
    actions:
      label:
        add: backport
      merge:
        method: merge
