version: 2
jobs:
  build:
    branches:
      only:
        - master
        - dev

    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
